### ISSUE TITLE
Error initializing plugin

### ISSUE THREAD

**Issue by JerichoTorrent** [KaspianDev/FishyBusiness#1]
Successfully builds, but error initializing:

```
[16:17:22 ERROR]: Error occurred while enabling FishyBusiness v1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/github/kaspiandev/pobox/mail/Mail
        at FishyBusiness-1.jar/com.github.kaspiandev.fishybusiness.hook.HookRegistry.<clinit>(HookRegistry.java:18) ~[FishyBusiness-1.jar:?]
        at FishyBusiness-1.jar/com.github.kaspiandev.fishybusiness.config.Config.lambda$loadEnabledHooks$3(Config.java:63) ~[FishyBusiness-1.jar:?]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at FishyBusiness-1.jar/com.github.kaspiandev.fishybusiness.config.Config.loadEnabledHooks(Config.java:62) ~[FishyBusiness-1.jar:?]
        at FishyBusiness-1.jar/com.github.kaspiandev.fishybusiness.config.Config.<init>(Config.java:44) ~[FishyBusiness-1.jar:?]
        at FishyBusiness-1.jar/com.github.kaspiandev.fishybusiness.FishyBusiness.onEnable(FishyBusiness.java:59) ~[FishyBusiness-1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-124-df3b654]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.github.kaspiandev.pobox.mail.Mail
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 18 more
[16:17:22 INFO]: [FishyBusiness] Disabling FishyBusiness v1
```

**Comment by KaspianDev** [comment]
Attach your config please

**Comment by JerichoTorrent** [comment]
Hi, sorry for the delayed response. I have deleted the config and rebuilt the plugin from source, so the config is completely fresh. I still get the same error.

**Comment by JerichoTorrent** [comment]
Yeah, once I actually used my brain I realized this plugin depends on your other plugin, POBox, but doesn't shade the jar. Upon installing POBox the plugin works. You can close this issue, but you may want to either shade it or add it as a listed dependency in your readme
